<a href="https://colab.research.google.com/github/vanditasharma777/Machine_Learning_algorithms_for_object_classification/blob/master/DecisionTree_RandomForest_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import necessary packages
import pandas as pd
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.datasets import mnist
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier 

In [ ]:
#provide dataset
(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()
print('x_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

x_train shape: (50000, 32, 32, 3)
50000 train samples
10000 test samples


In [ ]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train = X_train / 255.0
X_test = X_test / 255.0

In [ ]:
X_train = X_train.flatten().reshape(X_train.shape[0], X_train.shape[1]*X_train.shape[2]*X_train.shape[3])
X_test = X_test.flatten().reshape(X_test.shape[0],X_test.shape[1]*X_test.shape[2]*X_test.shape[3])

In [ ]:
rtc = RandomForestClassifier()
print("Train model")
rtc.fit(X_train, Y_train.ravel())
print("Compute predictions")
predictc = rtc.predict(X_test)
#Evaluation
print("Confusion matrix")
print(confusion_matrix(predictc,Y_test.ravel()))
print("Classification report")
print(classification_report(predictc,Y_test.ravel()))

Train model
Compute predictions
Confusion matrix
[[566  34  99  52  52  37   8  47  85  51]
 [ 37 561  33  44  21  26  37  50  85 150]
 [ 48  17 339  77 128  92  78  49  14  18]
 [ 18  40  70 289  58 161  81  65  29  33]
 [ 28  19 149  66 398  62 107  97  29  16]
 [ 26  27  65 168  42 388  56  82  34  22]
 [ 26  40 115 143 152  88 552  51  18  26]
 [ 30  36  74  67  99  86  32 448  18  37]
 [165  56  30  24  27  24  10  20 610  80]
 [ 56 170  26  70  23  36  39  91  78 567]]
Classification report
              precision    recall  f1-score   support

           0       0.57      0.55      0.56      1031
           1       0.56      0.54      0.55      1044
           2       0.34      0.39      0.36       860
           3       0.29      0.34      0.31       844
           4       0.40      0.41      0.40       971
           5       0.39      0.43      0.41       910
           6       0.55      0.46      0.50      1211
           7       0.45      0.48      0.46       927
           

NameError: ignored

In [ ]:
print("Accuracy: ")
print(accuracy_score(predictc, Y_test.ravel()))

Accuracy: 
0.4718


In [ ]:
dtf1 = DecisionTreeClassifier()
print("Train model")
dtf1.fit(X_train, Y_train.ravel())
print("Compute predictions")
predicted2 = dtf1.predict(X_test)
#Evaluation
print("Confusion matrix")
print(confusion_matrix(predicted2,Y_test.ravel()))
print("Classification report")
print(classification_report(predicted2,Y_test.ravel()))
print("Accuracy: ")
print(accuracy_score(predicted2, Y_test.ravel()))

Train model
Compute predictions
Confusion matrix
[[338  74 104  71  56  54  39  72 148  91]
 [ 80 267  48  57  48  54  44  71 105 168]
 [ 78  71 218 128 157 104 150  92  52  60]
 [ 51  79  94 173  90 142 124  99  44  49]
 [ 75  50 134 107 226  92 135  92  52  54]
 [ 50  59 114 126 117 225  93 101  46  62]
 [ 37  57 108 136 113 110 280  64  27  51]
 [ 55  63  89  96 102  91  62 270  38  95]
 [157 112  42  46  34  74  28  62 386  97]
 [ 79 168  49  60  57  54  45  77 102 273]]
Classification report
              precision    recall  f1-score   support

           0       0.34      0.32      0.33      1047
           1       0.27      0.28      0.27       942
           2       0.22      0.20      0.21      1110
           3       0.17      0.18      0.18       945
           4       0.23      0.22      0.22      1017
           5       0.23      0.23      0.23       993
           6       0.28      0.28      0.28       983
           7       0.27      0.28      0.28       961
           

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

x_train shape: (60000, 784)
60000 train samples
10000 test samples


In [ ]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train.shape


(10000, 784)

In [ ]:
x_test.shape

(10000, 784)

In [ ]:
x_train = x_train / 255.0
x_test = x_test / 255.0
x_train.shape

(60000, 784)

In [ ]:
x_train = x_train.flatten().reshape(x_train.shape[0], x_train.shape[1]*x_train.shape[2])
x_test = x_test.flatten().reshape(x_test.shape[0],x_test.shape[1]*x_test.shape[2])

In [ ]:
x_train.shape


(10000, 784)

In [ ]:
x_test.shape

(10000, 784)

In [ ]:
clf = RandomForestClassifier()
print("Train model")
clf.fit(x_train, y_train.ravel())
print("Compute predictions")
predicted = clf.predict(x_test)
#Evaluation
print("Confusion matrix")
print(confusion_matrix(predicted,y_test.ravel()))
print("Classification report")
print(classification_report(predicted,y_test.ravel()))

Train model
Compute predictions
Confusion matrix
[[ 971    0    7    1    1    5    5    1    5    7]
 [   0 1120    0    0    0    0    4    2    1    4]
 [   0    5  993   12    4    3    0   20    7    3]
 [   0    1    9  966    0   17    0    1    8    8]
 [   0    1    0    1  951    4    5    6    9   12]
 [   1    1    1    6    0  846    7    0    5    3]
 [   5    5    1    0    6    8  931    0    3    0]
 [   1    0    8    9    1    1    0  979    3    6]
 [   2    2   12   12    4    2    6    2  926    6]
 [   0    0    1    3   15    6    0   17    7  960]]
Classification report
              precision    recall  f1-score   support

           0       0.99      0.97      0.98      1003
           1       0.99      0.99      0.99      1131
           2       0.96      0.95      0.96      1047
           3       0.96      0.96      0.96      1010
           4       0.97      0.96      0.96       989
           5       0.95      0.97      0.96       870
           6       

In [ ]:
print("Accuracy: ")
print(accuracy_score(predicted, y_test.ravel()))

Accuracy: 
0.9643


In [ ]:
dtf = DecisionTreeClassifier()
print("Train model")
dtf.fit(x_train, y_train.ravel())
print("Compute predictions")
predicted1 = dtf.predict(x_test)
#Evaluation
print("Confusion matrix")
print(confusion_matrix(predicted1,y_test.ravel()))
print("Classification report")
print(classification_report(predicted1,y_test.ravel()))

Train model
Compute predictions
Confusion matrix
[[ 895    1   15    9    6   11   12    2   12    5]
 [   3 1096   13    5    3    8    7    6    9    7]
 [   6    5  875   27   15    9    5   29   25    7]
 [   8    5   36  833    7   45    3   11   36   14]
 [   6    2   17   15  846   23   20   13   29   39]
 [   8    2   13   45    7  718   17    4   33   15]
 [  19    6   11    4   19   15  866    0   15    1]
 [  10    0   17   17    9    8    1  909   13   41]
 [  13   14   28   33   19   38   24    9  779   22]
 [  12    4    7   22   51   17    3   45   23  858]]
Classification report
              precision    recall  f1-score   support

           0       0.91      0.92      0.92       968
           1       0.97      0.95      0.96      1157
           2       0.85      0.87      0.86      1003
           3       0.82      0.83      0.83       998
           4       0.86      0.84      0.85      1010
           5       0.80      0.83      0.82       862
           6       

In [ ]:
print("Accuracy: ")
print(accuracy_score(predicted1, y_test.ravel()))

Accuracy: 
0.8675
